### ISSUE TITLE
password policy when updating / patching

### ISSUE THREAD

**Issue by musicformellons** [kalisio/kCore#123]
Looks like on password update / patch the [password policy is not enforced / not in the hook ](https://github.com/kalisio/kCore/blob/e79d074ddc5206d86b7ece3ae6905ab968a3c680/src/services/users/users.hooks.js#L37)?

**Comment by claustres** [comment]
The reason is that while user registration is provided out-of-the-box by the core module, changing the password is not implemented by default and usually performed using a dedicated operation, which updates the user data internally (so we update the previous password list here). As a consequence the password policy should be enforced by the top-level operation.

Typically we rely on [f-a-m](https://github.com/feathers-plus/feathers-authentication-management) in [kNotify account service](https://github.com/kalisio/kNotify/blob/master/src/services/account/account.hooks.js#L10). If you don't have a dedicated operation then you can add the hook to enforce the policy on the user service patch/update operation at application level.

Hope this helps.
