### ISSUE TITLE
Async configure needed for what exactly?

### ISSUE THREAD

**Issue by musicformellons** [kalisio/kCore#75]
Standard Feathers configure is overridden [here](https://github.com/kalisio/kCore/blob/f9de28a3d54544ca3396ab29c3109cf9ba75df55/src/application.js#L444). For what operations exactly do we need async configure?

**Comment by claustres** [comment]
In a complex app you often need to control the initialization flow so that dependent modules play well together, and only the app can know the right ordering. A specific use case is the team module that initializes all org services based on orgs retrieved in the DB, which is a async operation: https://github.com/kalisio/kTeam/blob/master/src/services/index.js#L12. If you'd like to be sure that all org services are available after the team module initialization you need something like this (events could also be used but it is a more complex approach IMHO for this use case)
